#!/usr/bin/env bash
# Create the .env files this project needs, with freshly generated secrets.
#
# WHY THIS IS A SCRIPT rather than files committed to the repository, or values
# pasted into a chat:
#
#   - Global Constraint 1: .env files are never written by tooling or an agent,
#     and infra/.env.example carries placeholders only.
#   - A secret that travels through a transcript, a terminal history or an issue
#     has already leaked. Generated here, on the machine that will use it, it
#     never exists anywhere else.
#
# The secrets are written straight to the file and never printed.
#
#   ./infra/scripts/init-env.sh                 # local development
#   ./infra/scripts/init-env.sh --prod          # the pilot server
#   ./infra/scripts/init-env.sh --db-port 55432 # when 5432 is already taken
#   ./infra/scripts/init-env.sh --api-port 3100 # when 3000 is already taken
#
# It refuses to overwrite an existing file, so it cannot destroy the secrets of
# a running deployment. Use --force only when you mean to rotate everything.
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

MODE="dev"
DB_PORT="5432"
API_PORT="3000"
FORCE="no"

while [ $# -gt 0 ]; do
  case "$1" in
    --prod) MODE="prod" ;;
    --dev) MODE="dev" ;;
    --db-port) DB_PORT="${2:?--db-port needs a value}"; shift ;;
    --api-port) API_PORT="${2:?--api-port needs a value}"; shift ;;
    --force) FORCE="yes" ;;
    -h|--help) sed -n '2,21p' "$0"; exit 0 ;;
    *) echo "Unknown option: $1" >&2; exit 2 ;;
  esac
  shift
done

command -v openssl >/dev/null || { echo "openssl is required" >&2; exit 1; }

# 48 bytes of CSPRNG output, base64. Comfortably past the 32-character floor.
secret() { openssl rand -base64 48 | tr -d '\n'; }

guard() {
  if [ -f "$1" ] && [ "$FORCE" != "yes" ]; then
    echo "REFUSING: $1 already exists." >&2
    echo "  Rotating its secrets would sign everyone out and, for" >&2
    echo "  BACKUP_PASSPHRASE, make every existing backup unreadable." >&2
    echo "  Delete it deliberately, or pass --force." >&2
    exit 1
  fi
}

# ---- Local development ----
if [ "$MODE" = "dev" ]; then
  TARGET="apps/api/.env"
  guard "$TARGET"

  umask 077   # created 600 from the outset, never briefly world-readable
  cat > "$TARGET" <<EOF
# Local development. Generated by infra/scripts/init-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Never commit this file. Never reuse these values in a deployment.

# Matches the development stack in infra/docker-compose.yml.
DATABASE_URL="postgresql://phc:phc_dev_only@localhost:${DB_PORT}/phc_track?schema=public"

JWT_SECRET="$(secret)"
ACCESS_TOKEN_TTL="15m"
REFRESH_TOKEN_TTL_DAYS="30"

# Accountability and retention. Not secret, and mirrored from production so a
# local run reflects the real configuration rather than reporting
# "Not yet designated" on GET /system/compliance.
PHC_DATA_CONTROLLER="Ogechukwu Eleodimuo"
PHC_DPO_NAME="Ogechukwu Eleodimuo"
PHC_DPO_CONTACT=""
PHC_RETENTION_GENERAL_YEARS=10
PHC_RETENTION_MATERNITY_YEARS=25
PHC_RETENTION_CHILD_UNTIL_AGE=18

PORT=${API_PORT}
CORS_ORIGINS="http://localhost:5173,http://localhost:4173"

# SMS is switched off for this deployment.
SMS_ENABLED=false
SMS_REMINDERS_ENABLED=false
EOF

  chmod 600 "$TARGET"   # explicit: --force truncates, keeping the old file's mode
  echo "Created $TARGET (permissions 600)."
  if command -v ss >/dev/null && ss -ltn 2>/dev/null | grep -q ":${API_PORT} "; then
    echo
    echo "WARNING: something is already listening on port ${API_PORT}." >&2
    echo "         The hub will fail to start. Re-run with --api-port <free port> --force." >&2
  fi
  echo
  echo "Next:"
  echo "  1. docker compose -f infra/docker-compose.yml up -d postgres"
  echo "  2. pnpm db:migrate && pnpm db:seed"
  echo "  3. pnpm dev:api        (terminal 1)"
  echo "  4. VITE_API_BASE_URL=http://localhost:${API_PORT}/api/v1 pnpm dev   (terminal 2)"
  [ "$DB_PORT" != "5432" ] && echo "  Note: using database port $DB_PORT. Match it in infra/docker-compose.yml."
  exit 0
fi

# ---- The pilot server ----
TARGET="infra/.env"
guard "$TARGET"

echo "Setting up the production environment. Three values cannot be generated."
echo
read -r -p "Public domain (e.g. phc.nnewinorth.ng): " PHC_DOMAIN
read -r -p "Email for TLS certificate notices: " PHC_ACME_EMAIL
read -r -p "DPO contact, a monitored address or number: " PHC_DPO_CONTACT
echo

[ -n "$PHC_DOMAIN" ] || { echo "The domain is required: Caddy needs it for a certificate." >&2; exit 1; }
[ -n "$PHC_ACME_EMAIL" ] || { echo "The certificate email is required." >&2; exit 1; }
if [ -z "$PHC_DPO_CONTACT" ]; then
  echo "WARNING: no DPO contact set. A Data Protection Officer nobody can reach" >&2
  echo "         does not satisfy the NDPA accountability principle. Set" >&2
  echo "         PHC_DPO_CONTACT in $TARGET before go-live." >&2
  PHC_DPO_CONTACT=""
fi

umask 077
cat > "$TARGET" <<EOF
# Production. Generated by infra/scripts/init-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
#
# NEVER COMMIT THIS FILE. Back up BACKUP_PASSPHRASE to your secret manager
# separately from the backups themselves: an encrypted backup stored next to its
# passphrase is not encrypted in any way that matters, and losing it means
# losing every backup.

# ---- Site ----
PHC_DOMAIN=${PHC_DOMAIN}
PHC_ACME_EMAIL=${PHC_ACME_EMAIL}

# ---- Accountability (NDPA 2023) ----
PHC_DATA_CONTROLLER=Ogechukwu Eleodimuo
PHC_DPO_NAME=Ogechukwu Eleodimuo
PHC_DPO_CONTACT=${PHC_DPO_CONTACT}

# ---- Retention ----
# Archival review, not automatic deletion. Clinical data is never hard-deleted.
PHC_RETENTION_GENERAL_YEARS=10
PHC_RETENTION_MATERNITY_YEARS=25
PHC_RETENTION_CHILD_UNTIL_AGE=18

# ---- Database ----
POSTGRES_USER=phc
POSTGRES_DB=phc_track
POSTGRES_PASSWORD=$(secret)

# ---- API ----
JWT_SECRET=$(secret)
ACCESS_TOKEN_TTL=15m
REFRESH_TOKEN_TTL_DAYS=30

# ---- Backups ----
BACKUP_PASSPHRASE=$(secret)
BACKUP_INTERVAL_SECONDS=86400
BACKUP_RETENTION_DAYS=30

# ---- SMS: switched off for this deployment ----
# Before ever setting SMS_ENABLED=true: sign a data processing agreement with
# the provider, have the Igbo templates reviewed by a native speaker, and start
# collecting SMS consent at registration.
SMS_ENABLED=false
SMS_REMINDERS_ENABLED=false
EOF

chmod 600 "$TARGET"   # explicit: --force truncates, keeping the old file's mode
echo "Created $TARGET (permissions 600). Secrets were generated locally and not printed."
echo
echo "Next:"
echo "  1. Copy BACKUP_PASSPHRASE into your secret manager, NOT beside the backups."
echo "  2. mkdir -p infra/backups && sudo chown 70:70 infra/backups"
echo "  3. Point DNS for ${PHC_DOMAIN} at this server."
echo "  4. Follow docs/operations/deployment-runbook.md from section 2."
